# Generated by Django 4.2 on 2023-05-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_olitel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField(auto_created=True)),
                ('producto', models.CharField(max_length=200)),
                ('precio', models.FloatField(null=True)),
            ],
        ),
    ]
