# Generated by Django 4.2 on 2023-05-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_olitel', '0004_rename_id_producto_productos_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cotizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotizacion', models.TextField()),
            ],
        ),
    ]
