# Generated by Django 4.2 on 2023-05-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_olitel', '0005_cotizaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='codigo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='creacion',
            field=models.DateTimeField(null=True),
        ),
    ]
