# Generated by Django 4.2 on 2023-05-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_olitel', '0007_cotizaciones_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciones',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
